### ISSUE TITLE
Add a web browser tab icon

### ISSUE THREAD

**Issue by star210** [star210/Website#1]
Yes please :)

**Comment by whg** [comment]
I think you're talking about a favicon.

By putting a file called `favicon.png` in the static folder.

Have a look at the [Wikipedia page](https://en.wikipedia.org/wiki/Favicon)  for favicons. I usually go for a 16 x 16 PNG, because that allows for transparency, but other formats work too.

**Comment by whg** [comment]
Looking at this, it's probably best if you have the file in an ICO format. See:

https://www.favicon-generator.org/
